"""Capture real hublot frames, with their colours, as the module the page renders.

Writes src/terminal-frames.ts on stdout. Needs pyte and a daemon with something
running on it:

    python3 scripts/capture-frame.py ../dist/hublot > src/terminal-frames.ts
"""
import json, os, pty, select, struct, sys, termios, time, fcntl
import pyte

COLS, ROWS = 104, 16

def capture(binary, keys, cols=COLS, rows=ROWS, settle=6.0):
    pid, fd = pty.fork()
    if pid == 0:
        os.environ["TERM"] = "xterm-256color"
        os.environ["COLORTERM"] = "truecolor"
        os.execv(binary, [binary])
    fcntl.ioctl(fd, termios.TIOCSWINSZ, struct.pack("HHHH", rows, cols, 0, 0))

    screen = pyte.Screen(cols, rows)
    stream = pyte.ByteStream(screen)

    def drain(seconds):
        end = time.time() + seconds
        while time.time() < end:
            r, _, _ = select.select([fd], [], [], 0.2)
            if not r:
                continue
            try:
                chunk = os.read(fd, 1 << 20)
            except OSError:
                return
            if b"\x1b]11;?" in chunk:
                os.write(fd, b"\x1b]11;rgb:0d0d/1111/1717\x1b\\")
            if b"\x1b[6n" in chunk:
                os.write(fd, b"\x1b[1;1R")
            stream.feed(chunk)

    drain(settle)
    for k in keys:
        os.write(fd, k.encode())
        drain(2.5)

    lines = []
    for y in range(rows):
        row = screen.buffer[y]
        runs, current = [], None
        for x in range(cols):
            ch = row[x]
            style = (ch.fg, ch.bold, ch.reverse)
            if current and current[0] == style:
                current[1].append(ch.data)
            else:
                if current:
                    runs.append(current)
                current = [style, [ch.data]]
        if current:
            runs.append(current)
        lines.append([
            {"t": "".join(text), "c": fg, "b": bool(bold), "r": bool(rev)}
            for (fg, bold, rev), text in runs
        ])

    os.write(fd, b"q")
    time.sleep(0.4)
    for closer in (lambda: os.close(fd), lambda: os.waitpid(pid, 0)):
        try:
            closer()
        except (OSError, ChildProcessError):
            pass
    return lines

# Each frame is captured at the size it is shown at: the hero spans the page,
# the two side-by-side ones live in half of it, and hublot drops its
# lower-priority columns on its own at the narrower width.
# Tall enough for the two-row dashboard, which is the header hublot draws from
# eighteen rows up: the graphs and the host breakdown are half the point of the
# screen, and a shorter capture shows the one-line fallback instead.
# Each frame is captured at the shape it is shown at. The page sizes the type
# to fit the width it has, so a frame captured wider than its column comes out
# smaller: the two beside a paragraph are taken at eighty columns, which is the
# narrowest hublot keeps its full tab labels at, and the hero gets the width of
# the page.
#
# Eighteen rows is the other threshold: below it hublot folds its dashboard
# into a single line, and the graphs are half of what these frames are for.
frames = {
    "containers": capture(sys.argv[1], [], cols=104, rows=20),
    # Compose is the second tab now, so this is "2" and not "5".
    "compose": capture(sys.argv[1], ["2"], cols=80, rows=18),
    # The disk frame is captured with a category expanded: the point of that
    # view is the list of objects a prune would take, not the totals.
    # Eighty-eight rather than eighty: at eighty the summary line, which is
    # what says how much of the disk is reclaimable, is cut mid-word.
    "disk": capture(
        sys.argv[1],
        ["6", "r", "j", "j", "j", "j", "j", "j", "\r"],
        cols=88,
        rows=18,
    ),
}


def compact(lines):
    """Drops what the component can infer: default colours and trailing blanks."""
    out = []
    for row in lines:
        runs = []
        for r in row:
            run = {"t": r["t"]}
            if r["c"] != "default":
                run["c"] = "#" + r["c"] if len(r["c"]) == 6 else r["c"]
            if r["b"]:
                run["b"] = 1
            if r["r"]:
                run["r"] = 1
            runs.append(run)
        while runs and not runs[-1]["t"].strip() and len(runs[-1]) == 1:
            runs.pop()
        out.append(runs)
    return out


HEADER = """// Generated by scripts/capture-frame.py: real frames from a real daemon, taken
// through a pty and kept as styled runs rather than as an image, so the page
// stays sharp at any zoom and weighs almost nothing.
//
// To refresh, with a workload running on the local daemon:
//   python3 scripts/capture-frame.py /path/to/hublot > src/terminal-frames.ts
// It needs pyte (pip install pyte).

/** One run of characters sharing a colour. */
export type Run = {
  /** The text itself. */
  t: string;
  /** Foreground colour, absent for the terminal default. */
  c?: string;
  /** Bold. */
  b?: number;
  /** Reverse video, which is how the selected row is drawn. */
  r?: number;
};

export type Frame = Run[][];

export const frames: Record<"containers" | "compose" | "disk", Frame> = """

data = {name: compact(lines) for name, lines in frames.items()}
sys.stdout.write(HEADER + json.dumps(data, separators=(",", ":"), ensure_ascii=False) + ";\n")
